import type { ConnectionGroup, ServerConnection, MonitorState } from "../../entities/server/model/types";
import type { TerminalTab } from "../../entities/terminal/model/types";

export const mockConnectionGroups: ConnectionGroup[] = [
  { id: "production", name: "Production" },
  { id: "staging", name: "Staging" },
  { id: "local", name: "Local" },
];

export const mockServers: ServerConnection[] = [
  {
    id: "prod-01",
    name: "prod-01",
    groupId: "production",
    host: "10.0.0.12",
    port: 22,
    user: "root",
    authType: "password",
    password: "mock-password",
    credentialStorage: "plain",
    favorite: true,
    lastConnectedAt: "2026-06-13 10:12",
    latencyMs: 32,
    status: "connected",
  },
  {
    id: "staging",
    name: "staging",
    groupId: "staging",
    host: "10.0.1.8",
    port: 22,
    user: "deploy",
    authType: "privateKey",
    privateKeyPath: "~/.ssh/id_ed25519",
    credentialStorage: "none",
    favorite: true,
    lastConnectedAt: "2026-06-13 09:30",
    latencyMs: 46,
    status: "connected",
  },
  {
    id: "dev-box",
    name: "dev-box",
    groupId: "local",
    host: "192.168.31.22",
    port: 22,
    user: "ay",
    authType: "password",
    credentialStorage: "none",
    favorite: false,
    lastConnectedAt: "2026-06-12 22:05",
    status: "disconnected",
  },
  {
    id: "local-vm",
    name: "local-vm",
    groupId: "local",
    host: "127.0.0.1",
    port: 2222,
    user: "dev",
    authType: "password",
    credentialStorage: "none",
    favorite: false,
    lastConnectedAt: "2026-06-10 18:22",
    status: "disconnected",
  },
];

export const mockMonitor: MonitorState = {
  cpu: 18,
  memory: 42,
  disk: 61,
  load: "0.42",
  uptime: "18d 4h",
};

export const mockTabs: TerminalTab[] = [
  {
    id: "tab-shell",
    title: "shell-1",
    cwd: "/var/www/app",
    status: "active",
    sftpFollowTerminalCwd: false,
    sftpFollowTerminalCwdStatus: "disabled",
    sftpHeightRatio: 0.38,
    sftp: {
      currentPath: "/var/www/app",
      loading: false,
      selectedCount: 2,
      transferSummary: "upload 42%",
      transferQueue: [
        {
          id: "mock-upload-app-log",
          direction: "upload",
          name: "app.log",
          status: "running",
          progress: 42,
          summary: "1/2",
        },
        {
          id: "mock-upload-package",
          direction: "upload",
          name: "package.json",
          status: "queued",
          summary: "等待上传",
        },
      ],
      entries: [
        { id: "public", name: "public", path: "/var/www/app/public", kind: "directory", size: "-", modified: "2026-06-13 10:12", mode: "drwxr-xr-x" },
        { id: "src", name: "src", path: "/var/www/app/src", kind: "directory", size: "-", modified: "2026-06-13 10:10", mode: "drwxr-xr-x" },
        { id: "package", name: "package.json", path: "/var/www/app/package.json", kind: "file", size: "3.2 KB", modified: "2026-06-13 10:09", mode: "-rw-r--r--" },
        { id: "log", name: "app.log", path: "/var/www/app/app.log", kind: "file", size: "12.4 MB", modified: "2026-06-13 10:11", mode: "-rw-r--r--" },
      ],
    },
    output: [
      "root@prod-01:/var/www/app# git status",
      "On branch main",
      "Your branch is up to date with 'origin/main'.",
      "",
      "root@prod-01:/var/www/app# pnpm build",
      "vite v6.0.3 building for production...",
      "✓ 128 modules transformed.",
      "",
      "$ ",
    ].join("\r\n"),
  },
  {
    id: "tab-deploy",
    title: "deploy",
    cwd: "/opt/release",
    status: "idle",
    sftpFollowTerminalCwd: false,
    sftpFollowTerminalCwdStatus: "disabled",
    sftpHeightRatio: 0.38,
    sftp: {
      currentPath: "/opt/release",
      loading: false,
      selectedCount: 0,
      transferSummary: "idle",
      transferQueue: [],
      entries: [
        { id: "current", name: "current", path: "/opt/release/current", kind: "directory", size: "-", modified: "2026-06-13 09:44", mode: "drwxr-xr-x" },
        { id: "release", name: "release-20260613.tar.gz", path: "/opt/release/release-20260613.tar.gz", kind: "file", size: "88.1 MB", modified: "2026-06-13 09:42", mode: "-rw-r--r--" },
      ],
    },
    output: [
      "deploy@prod-01:/opt/release$ ./deploy.sh --dry-run",
      "Checking artifact...",
      "Checking service health...",
      "Ready to deploy.",
      "",
      "$ ",
    ].join("\r\n"),
  },
  {
    id: "tab-logs",
    title: "logs",
    cwd: "/var/log",
    status: "warning",
    sftpFollowTerminalCwd: false,
    sftpFollowTerminalCwdStatus: "disabled",
    sftpHeightRatio: 0.38,
    sftp: {
      currentPath: "/var/log",
      loading: false,
      selectedCount: 1,
      transferSummary: "download queued",
      transferQueue: [],
      entries: [
        { id: "nginx", name: "nginx", path: "/var/log/nginx", kind: "directory", size: "-", modified: "2026-06-13 08:55", mode: "drwxr-xr-x" },
        { id: "syslog", name: "syslog", path: "/var/log/syslog", kind: "file", size: "34.6 MB", modified: "2026-06-13 10:14", mode: "-rw-r-----" },
      ],
    },
    output: [
      "root@prod-01:/var/log# tail -f syslog",
      "Jun 13 10:12:02 prod-01 app[4821]: health check ok",
      "Jun 13 10:13:02 prod-01 app[4821]: queue depth 12",
      "",
      "$ ",
    ].join("\r\n"),
  },
];
